# Generated by Django 5.1.6 on 2025-03-01 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dish_photos/')),
                ('dish_type', models.CharField(choices=[('cold_appetizer', 'Холодная закуска'), ('hot_appetizer', 'Горячая закуска'), ('salad', 'Салат'), ('first_course', 'Первое блюдо'), ('main_course', 'Основное блюдо'), ('dessert', 'Десерт'), ('drink', 'Напиток')], max_length=20)),
                ('technology', models.TextField(blank=True)),
                ('ingredients', models.JSONField(default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
